### ISSUE TITLE
Error lauching evohome image

### ISSUE THREAD

**Issue by JFaqwz** [tico24/evohome-grafana#5]
Hi,

I'm trying to run the images but run into an issue on the evohomeclient image

```
Starting

Connected to InfluxDB

Database EH-TEMPS exists

Collect and store evohome temperatures

Starting

Traceback (most recent call last):

  File "/tmp/evohome.py", line 26, in <module>

    for device in eclient.temperatures():

  File "/usr/local/lib/python3.10/site-packages/evohomeclient2/controlsystem.py", line 112, in temperatures

    "temp": self.hotwater.temperatureStatus["temperature"],

KeyError: 'temperature'
```

Would you have any idea on what's wrong ? :/ 
I checked my HW username/password which look ok...

**Comment by tico24** [comment]
I don't have an immediate answer for you, but it looks like this is an error generated by the base evohome python stuff: https://github.com/watchforstock/evohome-client

Specifically here: https://github.com/watchforstock/evohome-client/blob/master/evohomeclient2/controlsystem.py#L112

I don't have a hotwater system so can't test this bit I'm afraid.

**Comment by JFaqwz** [comment]
Was caused by phantom zone with void text. Calling Honeywell to remove it made it work
